VALIDATION_KEYWORDS = {
    "City": [
        "city",
        "cities",
        "town",
        "settlement",
        "municipality",
        "stadt",
        "gemeinde",
        "siedlung",
        "ortschaft",
    ],
    "Country": [
        "country",
        "countries",
        "nation",
        "state",
        "republic",
        "sovereign state",
        "land",
        "staat",
        "nation",
        "republik",
        "bundesstaat",
    ],
    "River": ["river", "rivers", "watercourse", "fluss", "wasserlauf", "strom"],
    "Plant": [
        "plant",
        "flora",
        "tree",
        "flower",
        "fungus",
        "shrub",
        "species of",
        "pflanze",
        "baum",
        "blume",
        "pilz",
        "strauch",
        "gewächs",
        "gattung",
    ],
    "Animal": [
        "animal",
        "fauna",
        "mammal",
        "bird",
        "insect",
        "fish",
        "reptile",
        "amphibian",
        "species of",
        "tier",
        "säugetier",
        "vogel",
        "insekt",
        "fisch",
        "reptil",
        "amphibie",
        "gattung",
    ],
}

CATEGORIES = list(VALIDATION_KEYWORDS.keys())
HISTORY_GAMES_TO_SHOW = 10
TIME_LIMIT = 60
FILEPATH = "game_results_by_round.csv"
